using System;

namespace GlobalPlatform.NET.Exceptions
{
    /// <summary>
    /// The exception that is thrown when the cryptogram provided by the card does not match the one
    /// generated by the off-card entity.
    /// </summary>
    public class CardCryptogramException : InvalidOperationException
    {
        public byte[] ReceivedCryptogram { get; set; }

        public byte[] GeneratedCryptogram { get; set; }

        public CardCryptogramException(string message) : base(message)
        {
        }
    }
}
